// How many threads (grouped letters/chains) show on one listing page.
export const PAGE_SIZE = 15;

export interface PageSlice<T> {
  items: T[];
  currentPage: number;
  totalPages: number;
  hasPrev: boolean;
  hasNext: boolean;
}

// Slices an already-sorted array into the requested page. Used by index.astro
// and tag/[tag].astro to render page 1 inline (so "/" and "/tag/x/" don't
// need a "/page/1/" redirect); pages 2+ are generated by the sibling
// "page/[page].astro" routes using Astro's built-in paginate() instead, kept
// in sync by using the same PAGE_SIZE constant.
export function sliceThreads<T>(items: T[], page = 1, pageSize = PAGE_SIZE): PageSlice<T> {
  const totalPages = Math.max(1, Math.ceil(items.length / pageSize));
  const currentPage = Math.min(Math.max(1, page), totalPages);
  const start = (currentPage - 1) * pageSize;
  return {
    items: items.slice(start, start + pageSize),
    currentPage,
    totalPages,
    hasPrev: currentPage > 1,
    hasNext: currentPage < totalPages,
  };
}
